# 官方推荐：不再写 version 字段

services:
  etcd1:
    image: registry.k8s.io/etcd:v3.6.4  # ✅ 使用官方最新 etcd 镜像 v3.6.4
    container_name: etcd1              # 容器名称，便于识别
    networks:
      - etcd-net                       # 加入自定义网络，节点间可互相访问
    ports:
      - "2379:2379"                    # etcd 客户端端口（对外读写操作）
      - "2380:2380"                    # etcd 集群通信端口（用于内部节点同步）
    environment:
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  etcd2:
    image: registry.k8s.io/etcd:v3.6.4
    container_name: etcd2
    networks:
      - etcd-net
    ports:
      - "22379:2379"
      - "22380:2380"
    environment:
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

  etcd3:
    image: registry.k8s.io/etcd:v3.6.4
    container_name: etcd3
    networks:
      - etcd-net
    ports:
      - "32379:2379"
      - "32380:2380"
    environment:
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new

# 自定义网络，确保 etcd1/2/3 可以通过服务名相互通信
networks:
  etcd-net:
    driver: bridge
